# Generated by Django 5.2.4 on 2025-07-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
