# Generated by Django 5.2.4 on 2025-07-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo_app', '0002_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
