# Generated by Django 5.2.4 on 2025-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo_app', '0003_student_is_active_student_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
