# Generated by Django 5.2.4 on 2025-07-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendo_app', '0005_student_groups_student_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendo_app.course'),
            preserve_default=False,
        ),
    ]
